requiredParams:
  name: KtCast Implementation
  description: Create Implementation Module

# optional
optionalParams:
  revision: 1
  category: fragment
  formFactor: mobile
  constraints:
    - kotlin
  screens:
    - new_module
  minApi: 24
  minBuildApi: 32

# required only for modules templates
predefinedFeatures:
  - enableModuleCreationParams:
      defaultPackageNamePrefix: me.s097t0r1.ktcast.feature

widgets:
  - booleanParameter:
      id: includeStarter
      name: Include starter for feature
      help: Generate starter interface
      default: false

globals:
  - stringParameter:
      id: buildModuleName
      value: ${__formattedModuleName.classToResource()}

recipe:
  - mkDirs:
      - ${srcOut}:
          - impl
  - instantiateAndOpen:
      from: root/src/main/java/package/di/FeatureComponent.kt.ftl
      to: ${srcOut}/impl/di/${__formattedModuleName}Component.kt
  - instantiate:
      from: root/src/main/java/package/di/FeatureComponentHolder.kt.ftl
      to: ${srcOut}/impl/di/${__formattedModuleName}ComponentHolder.kt
  - instantiate:
      from: root/src/main/java/package/di/FeatureModule.kt.ftl
      to: ${srcOut}/impl/di/${__formattedModuleName}Module.kt
  - instantiate:
      from: root/build.gradle.ftl
      to: ${rootOut}/build.gradle
  - instantiate:
      from: root/.gitignore.ftl
      to: ${rootOut}/.gitignore
  - instantiate:
      from: root/src/main/AndroidManifest.xml.ftl
      to: ${rootOut}/src/main/AndroidManifest.xml