on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '41 17 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  static_analysis:
    name: Run static analyses on code
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'
      - name: Run detekt
        run: ./gradlew detekt
      - name: Sarif
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
