on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '41 17 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  static_analysis:
    name: Run static analyses on code
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'
      - name: Run detekt
        run: ./gradlew detekt reportMerge --continue
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@b398f525a5587552e573b247ac661067fafa920b # tag=v2
        if: ${{ always() }}
        with:
            sarif_file: build/detekt-report.sarif
